### PR TITLE
Readme/example fix

### PR DESCRIPTION
**Pull request by samcrudge**
## what
* Describe high-level what changed as a result of these commits (i.e. in plain-english, what do these changes mean?)
* Example of 'Origin Group with the origin created by this module as a primary origin and an additional
S3 bucket as a failover origin' showed the s3_origins & origin_group as a map(any) rather than a list(map) causing builds to fail when using said example.

## why
* Provide the justifications for the changes (e.g. business case). 
* Describe why these changes were made (e.g. why do these commits fix the problem?)
* Examples that reflect the required schema.

## references
* Link to any supporting github issues or helpful documentation to add some context (e.g. stackoverflow). 
* [README.md](https://github.com/cloudposse/terraform-aws-cloudfront-s3-cdn/blob/master/README.md) & [README.yaml](https://github.com/Cyber-Duck/terraform-aws-cloudfront-s3-cdn/blob/master/README.yaml)

### CODE REVIEW

**Comment by joe-niland** [comment]
@samcrudge apologies that this was missed - did you want to merge in the main branch so we can get this one merged?

**Comment by samcrudge** [comment]
Il do that today

**Comment by samcrudge** [comment]
@joe-niland I've synced the branches. do you need me to run any commands?

**Review by joe-niland — APPROVED** [review]

**Comment by joe-niland** [comment]
Thanks for your contribution @samcrudge !

**Pull request merged**
