### PR TITLE
Use canonical user Id instead of iam user to fix s3 invalid policy issue

### PR DESCRIPTION
**Pull request by hemanthudimella**
This PR fixes https://github.com/cloudposse/terraform-aws-cloudfront-s3-cdn/issues/50

### CODE REVIEW

**Comment by gyoza** [comment]
This will cause your applies to change the policy on every run.

**Comment by hemanthudimella** [comment]
Done. Rebuilt README.

**Comment by aknysh** [comment]
@hemanthudimella 
please see comments from @gyoza  https://github.com/cloudposse/terraform-aws-cloudfront-s3-cdn/pull/51#issuecomment-533594653

you just need to replace ” “, “_” on the old value

**Comment by hemanthudimella** [comment]
@gyoza @aknysh 
Did you mean replace manually? That means every time I apply a change, terraform removes my manual change, and I will have to do it again.
And if you didn't mean manual, please note that replacing " " with "_" works for all new policies. But any policies that are existing wouldn't accept "_" and `terraform apply` fails. (Existing policies are still accepting " " and " " only)
From my chat with  AWS support, the recommended way is to use canonical user id instead.
They were also mentioning that the syntax is not yet finalized and we can expect the "_" to be replaced or removed in future without any notice as they replaced " " with "_" without notice.
However I agree that `terraform plan` will always show a change in the policy, if we use canonical user id (even though there is no change in the policy). Hopefully terraform fixes this soon.
But until then using canonical user id is the only way (at least as far as i know) to make both existing and new policies work.

**Comment by gyoza** [comment]
Just commenting on what I found when I encountered this issue.

 Our CICD process does "things" when terraform reports items to change. So
when this is happening when there are actually no changes is somewhat a big
deal.

This is probably a problem for more than just our process.

For now I've opted to fork this module and hardcode appropriate changes
until the provider is fixed.

**Comment by hemanthudimella** [comment]
@gyoza Same here. I ended up forking the module. :)
@aknysh I suppose this module, at the moment, is unusable as is.

**Comment by aknysh** [comment]
@hemanthudimella 
please run `terraform fmt` (our CI/CD tests are failing).
After that, we'll merge the PR

**Comment by aknysh** [comment]
@hemanthudimella  please rebase and run `terraform fmt` and then rebuild README:

make init
make readme/deps
make readme
```

**Comment by maximmi** [comment]
@hemanthudimella is this PR still actual due to changes made and merged after this one?

**Comment by hemanthudimella** [comment]
Redundant PR

**Pull request closed without merging**
