### PR TITLE
Allow creating a policy for an existing S3 bucket

### LINKED ISSUE #152: Unable to override policy of existing S3 bucket
## Describe the Bug
When using the `origin_bucket` and `override_origin_bucket_policy` inputs, I consistently got the following error:

```
│ Error: Error putting S3 policy: InvalidParameter: 1 validation error(s) found.
│ - minimum field size of 1, PutBucketPolicyInput.Bucket.
│
│
│   on .terraform/modules/cdn/main.tf line 79, in resource "aws_s3_bucket_policy" "default":
│   79: resource "aws_s3_bucket_policy" "default" {
│
╵
```

## Expected Behavior
I was expecting the resulting generated AWS objects to use my provided S3 bucket with it's policy replaced with that of the automagically generated policies equivalent to what would have happened if I'd had the module create the bucket.

## Steps to Reproduce
1. Create a terraform module resource using both `origin_bucket` and `override_origin_bucket_policy`
2. Run `terraform apply`

## Environment (please complete the following information):

This happened initially with version `0.52.0`, but I also tried it with `0.58.1` and `0.59.0`

## Additional Context

What I think is happening is that the `bucket` attribute of the `aws_s3_bucket_policy` resource is required, and the code for the `aws_s3_bucket_policy.default` in `main.tf` is:

```
resource "aws_s3_bucket_policy" "default" {
   count  = (module.this.enabled && (! local.using_existing_origin || var.override_origin_bucket_policy)) ? 1 : 0
   bucket = join("", aws_s3_bucket.origin.*.bucket)
   policy = local.iam_policy_document
}
```

But if you are providing an external, preexisting S3 bucket, `aws_s3_bucket.origin.*.bucket` isn't going to have a value.

Lower down in the code, in the second `locals` block, there is a `bucket` variable defined like so:

```
bucket = join("",
  compact(
    concat([var.origin_bucket], concat([""], aws_s3_bucket.origin.*.id))
  )
)
```

If I set the `bucket` attribute in `aws_s3_bucket_policy.default` to `local.bucket`, I am able to cleanly apply, as now bucket contains *at least* my externally supplied bucket.

There may be subtleties I'm missing, but this seems to be the crux of things.

### PR DESCRIPTION
**Pull request by emyller**
## what
* Fix creating a S3 bucket policy when using an existing S3 bucket.

## why
* The code was only considering the bucket object managed by this module.

## references
* Closes #152.

### CODE REVIEW

**Review by nitrocode — DISMISSED** [review]

**Comment by emyller** [comment]
@nitrocode I can't make complete sense out of the errors pointed by CI. Would you give me a hint at how to fix these?

**Comment by nitrocode** [comment]
Try the following to kick off the build

```
git commit --allow-empty
git push -f
```

**Comment by emyller** [comment]
@nitrocode No luck. The log complains it can't push to my repo, or so it looks like:

```
+ git push
remote: Permission to continuumvip/terraform-aws-cloudfront-s3-cdn.git denied to cloudpossebot.
fatal: unable to access 'https://github.com/continuumvip/terraform-aws-cloudfront-s3-cdn/': The requested URL returned error: 403
```

Should the bot really be trying to do that?

**Comment by nitrocode** [comment]
Yes it should as that's how the Auto Format works. It clones your repo, checks if formatting is necessary, and then pushes up any changes.

You can format the code yourself and it will bypass that bot if you like or you can give your fork permission to the cloudposse bot.

**Comment by emyller** [comment]
> (...) or you can give your fork permission to the cloudposse bot.

Cool, that makes sense. I have invited the bot to the repository as a contributor, it's pending the invite. Can you please accept it and let me know so we can try triggering CI again? Thanks!

**Comment by pearsonhenri** [comment]
Anything I can do to help on this PR? Would looove to pull these changes in :)

**Comment by emyller** [comment]
@pearsonhenri I think we need Cloudposse to accept the invite to their bot account so it can push to the fork, or a volunteer to set up their linting environment locally and contribute with the necessary changes -- sorry I don't have time to do the latter. Right now this is basically how I'm using this module and it's fine:

```hcl
module "my_cdn" {
  # source = "cloudposse/cloudfront-s3-cdn/aws"
  # version = "0.59.0"
  source = "github.com/continuumvip/terraform-aws-cloudfront-s3-cdn?ref=2f24a73"
  ...
}
```

**Review by Gowiem — DISMISSED** [review]

**Comment by Gowiem** [comment]
@emyller you can run the formatting code yourself by doing the following: 

```
make init 
make pr/auto-format
```

Then commit your changes and push the result and that should get this passed that annoying auto-format bit. 

Apologies for the delay, please ping me directly once you've done the above steps or post in #pr-reviews in the SweetOps Slack and somebody else will get to it.

**Comment by emyller** [comment]
> Then commit your changes and push the result and that should get this passed that annoying auto-format bit.

Thanks @Gowiem. Can you please re-add your review?

**Review by Gowiem — APPROVED** [review]

**Comment by Gowiem** [comment]
Thanks for the contribution @emyller! Released as [0.62.0](https://github.com/cloudposse/terraform-aws-cloudfront-s3-cdn/releases/tag/0.62.0).

**Comment by pearsonhenri** [comment]
Yay thanks y'all!

**Pull request merged**
