### PR TITLE
Add support for website config on origin

### PR DESCRIPTION
**Pull request by dmattia**
This code is heavily inspired by https://github.com/cloudposse/terraform-aws-s3-website

This is in response to https://github.com/cloudposse/terraform-aws-cloudfront-s3-cdn/issues/14

### CODE REVIEW

**Comment by dmattia** [comment]
Thanks for the review @aknysh, I rebuilt the README.md and formatted the code

**Comment by aknysh** [comment]
@dmattia  please rebase

**Comment by aknysh** [comment]
@dmattia please rebase

**Comment by dmattia** [comment]
Just rebased @aknysh, thanks!

**Comment by aknysh** [comment]
@dmattia  please rebase again and rebuild README, thanks

**Comment by dmattia** [comment]
@aknysh just rebased and rebuilt

**Pull request merged**
