### PR TITLE
Fix sensitive values in outputs

### LINKED ISSUE #182: Sensitive outputs
## Describe the Bug
When running terragrunt apply:
Error: Output refers to sensitive values
│
│   on outputs.tf line 46:
│   46: output "cf_origin_ids" {
│
│ To reduce the risk of accidentally exporting sensitive data that was
│ intended to be only internal, Terraform requires that any root module
│ output containing sensitive data be explicitly marked as sensitive, to
│ confirm your intent.
│
│ If you do intend to export this data, annotate the output value as
│ sensitive by adding the following argument:
│     sensitive = true

## Expected Behavior
Terragrunt apply works

## Steps to Reproduce
I use the following options:
`website_enabled                    = true
  s3_website_password_enabled        = true
  versioning_enabled                 = true
  block_origin_public_access_enabled = true
  allow_ssl_requests_only            = false # https://github.com/cloudposse/terraform-aws-cloudfront-s3-cdn/issues/175

  cloudfront_access_log_create_bucket = false
  cloudfront_access_log_bucket_name = dependency.logging_bucket.outputs.s3_bucket_id`

## Environment (please complete the following information):
Module version: 0.74.3
Terraform version:
λ terraform -v
Terraform v1.0.0
on windows_amd64
+ provider registry.terraform.io/hashicorp/aws v3.55.0
+ provider registry.terraform.io/hashicorp/local v2.1.0
+ provider registry.terraform.io/hashicorp/random v3.1.0

### PR DESCRIPTION
**Pull request by sebastianmacarescu**
https://github.com/cloudposse/terraform-aws-cloudfront-s3-cdn/issues/182
## references
* `closes #182 `

### CODE REVIEW

**Comment by sebastianmacarescu** [comment]
Can we get this merged?

**Comment by nitrocode** [comment]
I believe `sensitive` is a terraform 0.15 feature

https://www.terraform.io/docs/language/functions/sensitive.html

> Note: This function is only available in Terraform v0.15 and later.

We're currently have a pin to allow this module to work on terraform 0.13 and above

https://github.com/cloudposse/terraform-aws-cloudfront-s3-cdn/blob/47d70f2f66272b0dd11984168463b2fcd02eb9a1/versions.tf#L1-L2

**Comment by nitrocode** [comment]
Here's something else that's also interesting. The `sensitive` flag isn't even on the `aws_cloudfront_distribution` resource's argument `origin.origin_id` schema

https://github.com/hashicorp/terraform-provider-aws/blob/e26f89a007dbddb3d967a3b506a129e6605f4846/aws/resource_aws_cloudfront_distribution.go#L568-L572

If the output was sensitive, shouldn't it have the `Sensitive: true` flag enabled for it like for [other resources](https://github.com/hashicorp/terraform-provider-aws/search?l=Go&q=sensitive) ?

**Pull request closed without merging**
