### PR TITLE
Fixed deprecated aws_s3_bucket attributes 

### PR DESCRIPTION
**Pull request by andruccho**
The following options were deprecated, and have either been updated, or replaced with the new necessary resources:

- `server_side_encryption_configuration` replaced with `aws_s3_bucket_server_side_encryption_configuration` resource
- `versioning` replaced with `aws_s3_bucket_versioning resource`
- `cors_rule` replaced with `aws_s3_bucket_cors_configuration resource`
- `acl` replaced with `aws_s3_bucket_acl resource`
- `bucket_versioning` input added

Pull request is almost the same with [#266](https://github.com/cloudposse/terraform-aws-cloudfront-s3-cdn/pull/266), exclude `override_json` replaced `with override_policy_documents` option, because for me it breaks `logs` submodule behavior.
I'm getting no deprecation warnings without this change (my `aws` provider version is `5.30.0`).

### CODE REVIEW

**Comment by ChrisBoik** [comment]
Came to do the same, thanks 👍

**Review by hans-d — APPROVED** [review]

**Pull request merged**
