### PR TITLE
Allow removing `origin` from the origin label

### PR DESCRIPTION
**Pull request by dmattia**
I also went ahead and did the same with "logs" on the log bucket.

These changes are backwards compatible, and would close https://github.com/cloudposse/terraform-aws-cloudfront-s3-cdn/issues/57

### CODE REVIEW

**Comment by dmattia** [comment]
Thanks for the review @aknysh, I rebuilt the README.md and formatted the code

**Comment by aknysh** [comment]
@dmattia 
thanks again!

All is good except the Terratest timeouts

```
test timed out after 30m0s
```


Here https://github.com/cloudposse/terraform-aws-cloudfront-s3-cdn/blob/master/test/src/Makefile#L45

Can you please update it to 60m timeout:

```
cd $(BASE) && go test -v -timeout 60m -run TestExamplesComplete
```

**Comment by dmattia** [comment]
Updated from 30m to 60m

**Pull request merged**
