### PR TITLE
Update bucket logging module version

### PR DESCRIPTION
**Pull request by okgolove**
Update to latest label module to support the environment attribute

## what
* Add compatibility with the latest label module's version

## why
* s3 bucket module has the same name in different environment

### CODE REVIEW

**Comment by okgolove** [comment]
Is it ok tests failed?

**Comment by Gowiem** [comment]
@okgolove I'd like to ensure they pass. Once #86 merges (should be later today) then we'll be good to go and I'll get this shipped. Sorry for the wait!

**Comment by Gowiem** [comment]
@okgolove Sorry to do it to ya, but it looks like there are some merge conflicts. Mind fixing and we'll get this merged?

**Comment by okgolove** [comment]
@Gowiem it seems I shouldn't run `make readme`. :)
I delete all changes related to README's.

**Comment by Gowiem** [comment]
@okgolove Thanks for the contribution! Released as [0.25.0](https://github.com/cloudposse/terraform-aws-cloudfront-s3-cdn/releases/tag/0.25.0).

**Pull request merged**
